import cuhk from "@/assets/images/chuk.png";

export const featuredInstitutions = [
    {
      slug: "slug-1",
      name: "The Chinese University of Hong Kong (CUHK)",
      location: "Hong Kong, Hong Kong SAR",
      image: cuhk,
      qsRank: "49",
      scholarship: "No",
      internationalStudents: "4367",
      intlStudents: 6347,
    },
    {
      slug: "slug-2",
      name: "The Chinese University of Hong Kong (CUHK)",
      location: "Hong Kong, Hong Kong SAR",
      image: cuhk,
      qsRank: "49",
      internationalStudents: "4367",
    },
    {
      slug: "slug-3",
      name: "The Chinese University of Hong Kong (CUHK)",
      location: "Hong Kong, Hong Kong SAR",
      image: cuhk,
      qsRank: "49",
      scholarship: "No",
      internationalStudents: "4367",
      intlStudents: 6347,
    },
    {
      slug: "slug-4",
      name: "The Chinese University of Hong Kong (CUHK)",
      location: "Hong Kong, Hong Kong SAR",
      image: cuhk,
      qsRank: "49",
      internationalStudents: "4367",
    },
    {
      slug: "slug-5",
      name: "The Chinese University of Hong Kong (CUHK)",
      location: "Hong Kong, Hong Kong SAR",
      image: cuhk,
      qsRank: "49",
      scholarship: "No",
      internationalStudents: "4367",
      intlStudents: 6347,
    },
    {
      slug: "slug-6",
      name: "The Chinese University of Hong Kong (CUHK)",
      location: "Hong Kong, Hong Kong SAR",
      image: cuhk,
      qsRank: "49",
      internationalStudents: "4367",
    },
  ];

export const programs = [
    {
      slug: "program-1",
      name: "Bachelor of Science in Computer Science",
      tuition: "$20,000",
      duration: "4 years",
      scholarship: "Yes",
      image: cuhk,
    },
    {
      slug: "program-2",
      name: "Bachelor of Science in Computer Science",
      tuition: "$20,000",
      duration: "4 years",
      scholarship: "Yes",
      image: cuhk,
    },
    {
      slug: "program-3",
        name: "Bachelor of Science in Computer Science",
        tuition: "$20,000",
        duration: "4 years",
        scholarship: "Yes",
        image: cuhk,
    },
    {
        slug: "program-4",
        name: "Bachelor of Science in Computer Science",
        tuition: "$20,000",
        duration: "4 years",
        scholarship: "Yes",
        image: cuhk,
    },
    {
        slug: "program-5",
        name: "Bachelor of Science in Computer Science",
        tuition: "$20,000",
        duration: "4 years",
        scholarship: "Yes",
        image: cuhk,
    },
    {
        slug: "program-6",
        name: "Bachelor of Science in Computer Science",
        tuition: "$20,000",
        duration: "4 years",
        scholarship: "Yes",
        image: cuhk,
    },
    {
        slug: "program-7",
        name: "Bachelor of Science in Computer Science",
        tuition: "$20,000",
        duration: "4 years",
        scholarship: "Yes",
        image: cuhk,
    },
    {
        slug: "program-8",
        name: "Bachelor of Science in Computer Science",
        tuition: "$20,000",
        duration: "4 years",
        scholarship: "Yes",
        image: cuhk,
    },
];

  export const articles = [
    {
      slug: "slug-1",
      title: "The Chinese University of Hong Kong (CUHK)",
      image: cuhk,
      date: "2023-10-01",
    },
    {
      slug: "slug-2",
      title: "The Chinese University of Hong Kong (CUHK)",
      image: cuhk,
      date: "2023-10-01",
    },
    {
      slug: "slug-3",
      title: "The Chinese University of Hong Kong (CUHK)",
      image: cuhk,
      date: "2023-10-01",
    },
    {
      slug: "slug-4",
      title: "The Chinese University of Hong Kong (CUHK)",
      image: cuhk,
      date: "2023-10-01",
    },
  ];